notes_manager_circle:
    resource: "@NotesManagerBundle/Resources/config/routing/circle.yml"
    prefix:   /circle

notes_manager_notes:
    resource: "@NotesManagerBundle/Resources/config/routing/notes.yml"
    prefix:   /notes
