notes_manager_circle:
    resource: "@NotesManagerBundle/Resources/config/routing/circle.yml"
    prefix:   /circle

notes_manager_notes:
    resource: "@NotesManagerBundle/Resources/config/routing/notes.yml"
    prefix:   /notes

notes_manager_sectors:
    resource: "@NotesManagerBundle/Resources/config/routing/sectors.yml"
    prefix:   /sectors

notes_manager_homepage:
    path:     /
    defaults: { _controller: NotesManagerBundle:Circle:index }
