# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Tzepart\NotesManagerBundle\Entity\Users: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        webservice:
            id: userProvider
                # if you're using multiple entity managers
                # manager_name: customer
    firewalls:
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        regster_firewall:
            pattern:   ^/register$
            anonymous: ~
        main:
            pattern:    ^/
            http_basic: ~
            provider: webservice
