security:
    encoders:
        Tzepart\NotesManagerBundle\Entity\User:
          algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: NotesManagerBundle:User
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login