# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Tzepart\NotesManagerBundle\Entity\Users:
          algorithm: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        webservice:
#            id: userProvider

    providers:
        our_db_provider:
            entity:
                class: NotesManagerBundle:Users
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
    firewalls:


#      default:
#        anonymous: ~
#        http_basic: ~

#        login_firewall:
#            pattern:   ^/login$
#            anonymous: ~
        regster_firewall:
            pattern:   ^/register$
            anonymous: ~

#        main:
#            pattern:    ^/
#            http_basic: ~
#            provider: our_db_provider

        main:
            anonymous: ~
            form_login:
              login_path: user_login
              check_path: user_login

#    access_control:
#    # require ROLE_ADMIN for /admin*
#    - { path: ^/admin, roles: ROLE_ADMIN }
