circle_index:
    path:     /
    defaults: { _controller: "AppBundle:Circle:index" }
    methods:  GET

circle_label_show:
    path:     /{id}/{labelId}/show
    defaults: { _controller: "AppBundle:Circle:show" }
    methods:  GET

circle_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Circle:show" }
    methods:  GET

circle_new:
    path:     /new
    defaults: { _controller: "AppBundle:Circle:new" }
    methods:  [GET, POST]

circle_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Circle:edit" }
    methods:  [GET, POST]

circle_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Circle:delete" }
    methods:  DELETE

circle_edit_label_ajax:
    path:     /editLabelAjax
    defaults: { _controller: "AppBundle:Circle:updateCoordinateLabel" }
    methods:  [GET, POST]
