services:
    app.circle_manager:
        class: AppBundle\Service\CircleManager
        arguments: [@service_container, @doctrine.orm.entity_manager]

    app.sector_manager:
        class: AppBundle\Service\SectorManager
        arguments: [@service_container, @doctrine.orm.entity_manager]

    app.layer_manager:
        class: AppBundle\Service\LayerManager
        arguments: [@service_container, @doctrine.orm.entity_manager]
