Tzepart\NotesManagerBundle\Entity\Circle:
    type: entity
    table: circle
    indexes:
        fk_circle_users1_idx:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            fixed: false
        dateCreate:
            type: datetime
            nullable: true
            column: date_create
        dateUpdate:
            type: datetime
            nullable: true
            column: date_update
    manyToOne:
        user:
            targetEntity: User
            inversedBy: circles
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        sectors:
            targetEntity: Sectors
            mappedBy: circle
        layers:
            targetEntity: Layers
            mappedBy: circle
    lifecycleCallbacks: {  }
