Tzepart\NotesManagerBundle\Entity\Colors:
    type: entity
    table: colors
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        color:
            type: string
            nullable: true
            length: 45
            fixed: false
        dateCreate:
            type: datetime
            nullable: true
            column: date_create
        dateUpdate:
            type: datetime
            nullable: true
            column: date_update
    lifecycleCallbacks: {  }
