Tzepart\NotesManagerBundle\Entity\Labels:
    type: entity
    table: labels
    indexes:
        fk_labels_sectors1_idx:
            columns:
                - sectors_id
        fk_labels_layers1_idx:
            columns:
                - layers_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        angle:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: angle
        radius:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: radius
        dateCreate:
            type: datetime
            nullable: true
            column: date_create
        dateUpdate:
            type: datetime
            nullable: true
            column: date_update
    manyToOne:
        sectors:
            targetEntity: Sectors
            inversedBy: labels
            cascade: {  }
            mappedBy: null
            joinColumns:
                sectors_id:
                    referencedColumnName: id
            orphanRemoval: false
        layers:
            targetEntity: Layers
            inversedBy: labels
            cascade: {  }
            mappedBy: null
            joinColumns:
                layers_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        notes:
          targetEntity: Notes
          mappedBy: labels
    lifecycleCallbacks: {  }
