Tzepart\NotesManagerBundle\Entity\Layers:
    type: entity
    table: layers
    indexes:
        fk_layers_circle1_idx:
            columns:
                - circle_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        beginRadius:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: begin_radius
        endRadius:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: end_radius
        dateCreate:
            type: datetime
            nullable: true
            column: date_create
        dateUpdate:
            type: datetime
            nullable: true
            column: date_update
        color:
            type: string
            nullable: true
            length: 10
            fixed: false
    manyToOne:
        circle:
            targetEntity: Circle
            inversedBy: layers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                circle_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        labels:
            targetEntity: Labels
            mappedBy: layers
    lifecycleCallbacks: {  }
