Tzepart\NotesManagerBundle\Entity\Notes:
    type: entity
    table: notes
    indexes:
        fk_notes_users_idx:
            columns:
                - users_id
        fk_notes_labels1_idx:
            columns:
                - labels_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 1024
            fixed: false
        text:
            type: text
            nullable: true
            length: null
            fixed: false
        dateCreate:
            type: datetime
            nullable: true
            column: date_create
        dateUpdate:
            type: datetime
            nullable: true
            column: date_update
    manyToOne:
        users:
            targetEntity: Users
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                users_id:
                    referencedColumnName: id
            orphanRemoval: false
        labels:
            targetEntity: Labels
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                labels_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
