Tzepart\NotesManagerBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 45
            fixed: false
        username:
            type: string
            nullable: false
            length: 45
            fixed: false
        password:
            type: string
            nullable: false
            length: 45
            fixed: false
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
        logged:
            type: datetime
            nullable: true
        roles:
            type: string
            nullable: true
            length: 45
            fixed: false
        homepage:
            type: string
            nullable: true
            length: 256
            fixed: false
        is_active:
            type: boolean
            nullable: false
        gravatar:
            type: string
            nullable: false
            length: 45
            fixed: false
    lifecycleCallbacks: {  }
