AppBundle\Entity\User:
    type: entity
    table: user
    attributeOverride:
        salt:
          column: salt
          type: string
          nullable: true
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
        updated:
            type: datetime
            nullable: false
        logged:
            type: datetime
            nullable: true
        isActive:
            type: boolean
            nullable: false
            column: is_active
    oneToMany:
            notes:
                targetEntity: Notes
                mappedBy: user
            circles:
                targetEntity: Circle
                mappedBy: user
    lifecycleCallbacks: {  }
