circle_index:
    path:     /
    defaults: { _controller: "NotesManagerBundle:Circle:index" }
    methods:  GET

circle_show:
    path:     /{id}/show
    defaults: { _controller: "NotesManagerBundle:Circle:show" }
    methods:  GET

circle_new:
    path:     /new
    defaults: { _controller: "NotesManagerBundle:Circle:new" }
    methods:  [GET, POST]

circle_edit:
    path:     /{id}/edit
    defaults: { _controller: "NotesManagerBundle:Circle:edit" }
    methods:  [GET, POST]

circle_delete:
    path:     /{id}/delete
    defaults: { _controller: "NotesManagerBundle:Circle:delete" }
    methods:  DELETE
